### PR TITLE
added additional tags to job instances

### PR DESCRIPTION
**Pull request by nisarg-soni**
Added tags for chain ID and contract address to the job instances

### CODE REVIEW

**Review by roshanr95 — CHANGES_REQUESTED** [review]
Use ethers instead of web3 since we already use it elsewhere. And pretty sure we can use the wss url itself to query, don't need to change it to http.

**Comment by roshanr95** [comment]
https://docs.rs/ethers/latest/ethers/providers/struct.Ws.html#method.request

**Review by arnav-deep — APPROVED** [review]

**Comment by nisarg-soni** [comment]
> Use ethers instead of web3 since we already use it elsewhere. And pretty sure we can use the wss url itself to query, don't need to change it to http.



> Use ethers instead of web3 since we already use it elsewhere. And pretty sure we can use the wss url itself to query, don't need to change it to http.

**Comment by nisarg-soni** [comment]
> Use ethers instead of web3 since we already use it elsewhere. And pretty sure we can use the wss url itself to query, don't need to change it to http.

Resolved

**Review by roshanr95 — CHANGES_REQUESTED** [review]
Add context to the errors

**Comment by nisarg-soni** [comment]
> Add context to the errors

Done

**Review by roshanr95 — APPROVED** [review]

**Pull request merged**
